### ISSUE TITLE
Is it possible to add a new dataset from the command line? 

### ISSUE THREAD

**Issue by JonathanReeve** [stain/jena-docker#10]
Thanks for posting this Docker image for Fuseki! It works great. I'm trying to automate a system which spins up a new container, adds all the data to it, and adds a new dataset. The instructions you provide, in the section "recognizing the data set in Fuseki," explain how to do this using the web GUI interface, but I'd like to be able to automate this using a Dockerfile, eventually. Do you know if there is a way to add a new dataset to fuseki on the command line? I've been trying things like `docker run --name fuseki -p 3030:3030 --volumes-from fuseki-data stain/jena-fuseki ./fuseki-server --loc=gut /gut` where `gut` is the name of the dataset, but it fails, saying "directory not found."

Thanks in advance for any help you might be able to provide!

**Comment by retog** [comment]
You might use curl:

```
curl 'http://localhost:3030/$/datasets' -H "Authorization: Basic $(echo -n admin:password | base64)" \
    -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'dbName=MyDataset&dbType=tdb'
```
