### ISSUE TITLE
Apache jena fuseki is not able to import .owl file

### ISSUE THREAD

**Issue by madrilen** [stain/jena-docker#11]
Hello,

I had the same error message when tried to upload an owl files in Apache jena fuseki:

![error](https://user-images.githubusercontent.com/6775649/42738606-5d6dd820-887e-11e8-9e77-f0212b36ce9e.jpg)
here the capture of one of my owl file
![owl file](https://user-images.githubusercontent.com/6775649/42738827-61de1998-8882-11e8-9370-6d3e77d28ae8.png)
 
Thanks for help

**Comment by stain** [comment]
So sorry I missed this from last year (!) You probably realized that `.owl` is not in an RDF syntax, and as Jena can import all of the RDF syntaxes. You can convert an OWL/XML to `.ttl` or `.rdf` using Protege or OWL API, and then import those in Jena Fuseki.
