### ISSUE TITLE
Apache Jena 3.9.0

### ISSUE THREAD

**Issue by barrynl** [stain/jena-docker#13]
Hi, 

would it be possible to make Apache Jena 3.7.0, 3.8.0 and 3.9.0 available via hub.docker.com? Currently, the latest version is 3.6.0.

Regards, Barry

**Comment by stain** [comment]
3.7.0, 3.9.0 and 3.10 now on https://cloud.docker.com/repository/registry-1.docker.io/stain/jena-fuseki/tag

3.8.0 missing somehow, will add it manually for completeness.
