### ISSUE TITLE
lucene indexing guide

### ISSUE THREAD

**Issue by fils** [stain/jena-docker#16]
So I am new to the Jena ecosystem for a triple store (coming from virtuoso, blaze and some others).

I'm really interested in combining Jena with Lucene.   Is Lucene a part of this Docker image?  Is lucene part of Jena in general now?   

If so I was curious if there was a guide on how to activate lucene on a database and connect various predicates to the index.   

Thanks..  any help or guidance appreciated..
Doug

**Comment by stain** [comment]
Sorry I missed this issue. Lucene is not part of Jena, but Jena can make use of it. I am not sure on how it can be enabled in a Fuseki distribution - it seems [quite a bit of configuration](https://jena.apache.org/documentation/query/text-query.html) is needed.

You should redirect any further questions on how to do this at the [Jena mailing list](http://jena.apache.org/help_and_support/index.html)
