### ISSUE TITLE
Dataset SPARQL endpoint

### ISSUE THREAD

**Issue by wood-chris** [stain/jena-docker#18]
This is likely to be me not understanding Jena and/or Docker, but I've noticed that the default SPARQL endpoint isn't available from a docker build. If I build & install Jena locally, then I can view

    http://localhost:3030/<dataset>/sparql

but building via docker gives a 404 error for that URL. All the other admin functions seem to work, and I can query via GET; for example, this works:

    http://localhost:3030/<dataset>/query?query=select%20(count(*)%20as%20?count)%20{?s%20?p%20?o}

I've tried both the 3.9.0 and 3.7.0 docker builds

**Comment by namedgraph** [comment]
@wood-chris we have another image, see if it helps: https://github.com/AtomGraph/fuseki-docker

**Comment by wood-chris** [comment]
Ah, I've just realised that default jena doesn't include SPARQLer (which is what I was thinking of!) - that'll be why the URL I was expecting to show a HTML view of a SPARQL endpoint returns a 404! (I've raised a query with Jena about this, because I thought SPARQLer was packaged with Fuseki)

**Comment by nmattela** [comment]
Is it possible to add SPARQLer to this docker image somehow? I am facing the same issue and @namedgraph 's image does not satisfy my needs. I also can't find much about SPARQler online to help me further either.

**Comment by namedgraph** [comment]
In the Docker world, SPARQLer is probably best as a separate image.
