### ISSUE TITLE
Running Fuseki under arm32v7

### ISSUE THREAD

**Issue by malakhovks** [stain/jena-docker#22]
Hello!
I want to run **Fuseki** on my SBC [NanoPi NEO Air](http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO_Air). It has **arm32v7** architecture.
I think it will work if just replace the base docker image with **arm32v7/openjdk:8-jre-alpine**
It would be nice to create a separate branch for this.

**Comment by stain** [comment]
Hi, 

That sounds a bit specialized and I would probably not be managing to maintain it well. I don't believe Docker Hub can do automated builds on the arm architecture. It's probably best if you fork this repository to do this as your own variant.

If the other image is also alpine based the rest of the Dockerfile should work as-is.
