### ISSUE TITLE
Running Fuseki with custom TDB Assembler

### ISSUE THREAD

**Issue by blankdots** [stain/jena-docker#3]
First of all: very helpful Docker files.
Not really issues more like questions:
1. How can I run the image with a custom TDB Assembler config like the ones at: https://jena.apache.org/documentation/tdb/assembler.html at start  ? 
2. looking to having the option of making the `tdb:location` of the graph as a Volume in a specified location on the host, should I reuse the `/fuseki` volume or add new one?

Might have some ideas on how to do this, however wanted to see if there is already some options available, which I might be missing.

**Comment by nimonika** [comment]
@blankdots Did you manage to find a solution?I am stuck with exactly the same issue.

**Comment by blankdots** [comment]
@nimonika you can take a look at this https://github.com/blankdots/docker-SemanticWebApps/tree/master/apache-fuseki I will try to write some instructions today or tomorrow.

**Comment by stain** [comment]
Welcome any pull requests - as for custom Assembler config then I don't think there's really any way to escape from either adding your own through a custom Dockerfile as you've done, or pre-populating it into the volume.  (Trying to generate it from sparse Docker shell variables would be tricky)
