### ISSUE TITLE
VOLUME /fuseki prevents derivative images from adding to /fuseki/extra

### ISSUE THREAD

**Issue by kvjrhall** [stain/jena-docker#39]
https://github.com/stain/jena-docker/blob/0074865d53f710d85f72af14c103aaef595a2244/jena-fuseki/Dockerfile#L47

After declaring `VOLUME /fuseki`, [any subsequent changes to the directory are discarded](https://forums.docker.com/t/simple-mkdir-p-not-working/42179/3). The official `fuseki-server` [recommends modifying `FUSEKI_BASE/extra`](https://github.com/apache/jena/blob/master/jena-fuseki2/apache-jena-fuseki/fuseki-server#L100-L121) to add additional libraries to the server. In a derived image, it [is not possible to undo the `VOLUME` declaration](https://stackoverflow.com/a/44020873/2528639). Consequently, creating a derived container that includes any additional jena/fuseki plugins requires copying this entire repository in order to remove said declaration.

For those who use this image directly, simply mounting a corresponding volume and adding the plugins on their host is a workaround, but requires that those tools be manually installed by an end user. I believe this would play more nicely with the larger docker ecosystem without the volume command, as users are not prevented from mounting that folder as a volume even without it.

**Comment by stain** [comment]
How about we bake in a symlink `/fuseki/extra` -> `/fuseki-extra` which can then be overriden in a Docker image, while if someone wants to do it classically they can replace the symlink in the volume with a folder? 

However that code you linked to would with an empty or non-existing directory then add literal `/fuseki/extra/*` to the classpath which probably won't work..  

Perhaps better the entrypoint can detect `/fuseki-extra` and add that symlink dynamically?
