### ISSUE TITLE
Current `load.sh` does not allow to specify other parameters for the tdbloader

### ISSUE THREAD

**Issue by kuzeko** [stain/jena-docker#42]
The script provides a list of files but does not allow to set other options, e.g.,  the graph name `--graph=https://example.org/graph#name`

https://github.com/stain/jena-docker/blob/0074865d53f710d85f72af14c103aaef595a2244/jena-fuseki/load.sh#L72

**Comment by stain** [comment]
Can we just add a "$@" before $files ?

**Comment by stain** [comment]
Could not easily do it with `"$@"` as `load.sh` takes a list of file patterns as arguments. Instead set environment variable which is probably more helpful for Dockerfile usage.

> Set the environment variable TDBLOADER_OPTS for any additional"
> options to pass to tdbloader, e.g. --graph=https://example.org/graph#name
