### ISSUE TITLE
Update to new fuseki versions?

### ISSUE THREAD

**Issue by infinite-dao** [stain/jena-docker#44]
Hej hej

is it possible to update the Dockerfile to the current fuseki version(s)? Or is it not regarded as important to update ?

There is also the `ps` command error in the new docker environment (triggered by fuseki) that should better be fixed see comment https://github.com/stain/jena-docker/issues/33#issuecomment-685630904

Kind regards
Infinite-dao

**Comment by stain** [comment]
Dockerfile was updated to 3.14.0, #54 is addressing update to 4.0. Sorry for the delay!
