### ISSUE TITLE
update Jena to v4.0

### ISSUE THREAD

**Issue by chihpoc** [stain/jena-docker#54]
apache-jena-4.0.0 was lately released, https://jena.apache.org/download/. any plan to update the Docker file to use Jena 4.0 in place of 3.17?

**Comment by stain** [comment]
There might be some changes to the command line tools but let's just try right away on our `master` (due rename to `main`?) which Docker Hub builds as `devel`.

I don't see from the [4.0.0 release notes](https://lists.apache.org/thread.html/r64bc917638f6964843181a95a2d92bfe8cf013b06eddf4402080669b%40%3Cusers.jena.apache.org%3E) any big changes in terms of Fuseki. Adding RDF* support would be nice!

**Comment by stain** [comment]
Changed my mind on the branches.. 

Making branch [jena4](https://github.com/stain/jena-docker/tree/jena4) for now, built with tag `jena4` for both Docker images.

**Comment by stain** [comment]
[Jena 4 build is happy](https://www.travis-ci.com/github/stain/jena-docker/builds/226797206) (after merging #52 #53), and likewise on Docker Hub.

Could some of you help try out a bit better than me?

```
(base) Ians-Mac-mini:~ stain$ docker run stain/jena:jena4 riot --version
Jena:       VERSION: 4.0.0
Jena:       BUILD_DATE: 2021-03-27T10:32:16+0000

(base) Ians-Mac-mini:~ stain$ docker run -p 3030:3030 -e ADMIN_PASSWORD=pw123 stain/jena-fuseki:jena4
…
09:35:40 INFO  Server          :: Apache Jena Fuseki 4.0.0
09:35:40 INFO  Config          :: FUSEKI_HOME=/jena-fuseki
09:35:40 INFO  Config          :: FUSEKI_BASE=/fuseki
09:35:41 INFO  Config          :: Shiro file: file:///fuseki/shiro.ini
09:35:42 INFO  Server          :: System
09:35:42 INFO  Server          ::   Memory: 4.0 GiB
09:35:42 INFO  Server          ::   Java:   11.0.11
09:35:42 INFO  Server          ::   OS:     Linux 4.19.121-linuxkit amd64
09:35:42 INFO  Server          ::   PID:    10
09:35:42 INFO  Server          :: Started 2021/05/25 09:35:42 UTC on port 3030
```

So far, so good! Tested validating and uploading a .jsonld file. Apache Jena is of course very good at keeping backwards compatibility even when bumping major version!

**Comment by stain** [comment]
Will tag and update tomorrow. Merged into `master` so you can also in a few minutes try on `devel` tag, which would include #51 for Ctrl-C support.
