### ISSUE TITLE
Query Issues

### ISSUE THREAD

**Issue by hantongliu** [stain/jena-docker#7]
Hi Stain,

I tried a query on your fuseki server, but it doesn't work.

```sparql
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX movie: <http://data.linkedmdb.org/resource/movie/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?film ?label ?subject WHERE {
SERVICE <http://data.linkedmdb.org/sparql> {
?film a movie:film .
?film rdfs:label ?label .
?film owl:sameAs ?dbpediaLink
FILTER(regex(str(?dbpediaLink), "dbpedia", "i"))
}
SERVICE <http://dbpedia.org/sparql> {
?dbpediaLink dcterms:subject ?subject
}
}
```

If I run seperately, it works. There is a common variable "?dbpediaLink". Wouldn't fuseki join the same varible together?

**Comment by stain** [comment]
(Edit: I modified your comment to include `<>` around the `PREFIX` and `SERVICE` statements -- I assume you tested with those in place)

I think you may face timeout issues as both `SERVICE` selects are quite broad and would fetch many thousands of entries. 

Another issue I think is that dbpedia uses URIs like `<http://dbpedia.org/resource/The_Rock_(film)>` while the linkedmdb.org uses %-encoding like `<http://dbpedia.org/resource/The_Rock_%28film%29>`

You have other broken data from linkedmdb.org, e.g. UTF-8-as-Latin1 "LÃ©on" when presumably it means "Léon".

You should try each endpoint separately. For instance, in the Fuseki UI you can change "SPARQL Endpoint" to `http://dbpedia.org/sparql` and then try:

```sparql
DESCRIBE <http://dbpedia.org/resource/The_Rock_(film)>
```

You can significantly filter what is returned from dbpedia by adding a class.

```sparql
PREFIX dbo:	<http://dbpedia.org/ontology/>  
  ...
  SERVICE <http://dbpedia.org/sparql> {
    ?dbpediaLink a dbo:Film ;
      dcterms:subject ?subject
  ..
```


As I was bored before lunch, here's a light-weight data cleaning query that gives some results (but misses lots of others):

```sparql
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX movie: <http://data.linkedmdb.org/resource/movie/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbo:	<http://dbpedia.org/ontology/> 

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX movie: <http://data.linkedmdb.org/resource/movie/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?film ?label ?subject ?dbPediaCleaned WHERE {
  SERVICE <http://data.linkedmdb.org/sparql> {
    ?film a movie:film .
    ?film rdfs:label ?label .
    ?film owl:sameAs ?dbpediaLink
    FILTER(regex(str(?dbpediaLink), "dbpedia", "i"))
  }
  BIND (IRI(REPLACE(REPLACE(STR(?dbpediaLink), 
          "%28", "("),
  	      "%29", ")"))
        AS ?dbPediaCleaned) 

  SERVICE <http://dbpedia.org/sparql> {
      ?dbPediaCleaned a dbo:Film ;
        dcterms:subject ?subject
  }
  
}

LIMIT 100
```


This seems to return some results.

I see there are other %-escapes in the `?dbpediaLink` that the above don't cover. I am not sure also if linekdmdb.org has naively added `(film)` to every URI even when that is not used in dbpedia.

You should rather take out the linkedmdb.org dbpedia links in a separate query and compare to a separate dbo:Film query and do this data cleaning manually outside Sparql.


If you have questions about Jena Fuseki, you should contact the [Apache Jena community](https://jena.apache.org/help_and_support/) - e.g. asking on their mailing lists.   This GitHub repository is mainly for making a Docker container of the official Fuseki releases.
