### ISSUE TITLE
Update to a newer version 4.1.0,  4.2.0,  4.3.0 aso.?

### ISSUE THREAD

**Issue by infinite-dao** [stain/jena-docker#70]
Hi,

is it possible to update to a newer version? 

I have an issue to move huge named GRAPH and the recommendation is to update to version 4.3.2 or 4.4.0
(see [lists.apache.org thread “MOVE GRAPH … TO GRAPH … ~  Server Error 500 Iterator: started at 5, now 6 (SPARQL Update)”](https://lists.apache.org/thread/y6m1ypjof0r2t28nnowqbwpvd9mpkfxt)).

Or is it otherwise possible to easily update fuseki itself? (probably from the Dockerfile or so, I’m not familiar with that)

Kind regards,
Andreas

**Comment by CarMoreno** [comment]
There is a [PR](https://github.com/stain/jena-docker/pull/63) to update the version but it has not been merged yet 😞

**Comment by kuzeko** [comment]
This should have been fixed now @infinite-dao

**Comment by kuzeko** [comment]
Like this?
https://phoenixnap.com/kb/docker-environment-variables#ftoc-heading-4

**Comment by kuzeko** [comment]
Sorry, I don't understand the issue, can you elaborate a bit more what is the issue now?

**Comment by infinite-dao** [comment]
I’m not so familiar and experienced  with docker aso., and it is difficult for me to see what command argument sets what variable on `docker build ` (build time) or later on `docker run --env …` or even with docker compose. 

Your afore mentioned example (https://phoenixnap.com/kb/docker-environment-variables#ftoc-heading-4) describes well the differences of `ARG` and `ENV` from which I can learn. My question aimed at a complete minimum example of how to setup a higher fuseki version than in this git repo, but I guess there is no magical easy way to do it (I thought I could set `docker run … --env FUSEKI_VERSION="4.7.0"  FUSEKI_SHA512="…"` but that was a misinterpreted assumption from my own thinking, so), except to:
 
1. clone the git repo locally
2. modify `ENV` in `Dockerfile`
3. do `docker build` with that modified 
4. create the fuseki app by `docker run …`

**Comment by infinite-dao** [comment]
So here is one way to setup an(y) other Fuseki version (not fully tested, but it worked at the time of writing)

```bash
custom_git_base=/my/custom/git-base4Jena-Apache/custom-setup

mkdir --parents "${custom_git_base}" \
  && cd "${custom_git_base}"

git clone https://github.com/stain/jena-docker.git

# copy original Dockerfile modify it FUSEKI_VERSION, FUSEKI_SHA512
cd "${custom_git_base}"/jena-docker/jena-fuseki/ \
  && cp Dockerfile Dockerfile-fuseki-4-7-0

# within the same directory
docker build --file Dockerfile-fuseki-4-7-0 \
  --tag jena-fuseki_customized-4-7-0 .
# Successfully tagged jena-fuseki_customized-4-7-0:latest

FUSEKI_APP=fuseki-app_test_fuseki_4-7-0
FUSEKI_DATA_APP=fuseki-data_test_fuseki_4-7-0

docker run --name "$FUSEKI_DATA_APP" --volume /fuseki busybox 
# set up port 8080 on localhost:8080 for testing
docker run --name "$FUSEKI_APP" --detach --publish 8080:3030 \
  --log-opt max-size=300m \
  --log-opt max-file=3 \
  --log-opt compress=true \
  --env ADMIN_PASSWORD="my-super-secret-password" \
  --env JVM_ARGS="-Xmx2g -Dlog4j2.formatMsgNoLookups=true"\
  --volume /path/to/my/import/data:/import-data \
  --volumes-from "$FUSEKI_DATA_APP" \
  jena-fuseki_customized-4-7-0:latest

docker logs "$FUSEKI_APP"
# ###################################
# Initializing Apache Jena Fuseki
# 
# 
# ###################################
# 14:56:17 INFO  Server          :: Apache Jena Fuseki 4.7.0
# 14:56:17 INFO  Config          :: FUSEKI_HOME=/jena-fuseki
# 14:56:17 INFO  Config          :: FUSEKI_BASE=/fuseki
# 14:56:17 INFO  Config          :: Shiro file: file:///fuseki/shiro.ini
# 14:56:18 INFO  Server          ::   Memory: 2.0 GiB
# 14:56:18 INFO  Server          ::   Java:   11.0.16
# 14:56:18 INFO  Server          ::   OS:     Linux 5.15.85-1-MANJARO amd64
# 14:56:18 INFO  Server          ::   PID:    11
# 14:56:18 INFO  Server          :: Started 2023/01/12 14:56:18 UTC on port 3030
```

Now the Fuseki Server should run as 4.7.0.

And remove the entire test 4.7.0 Fuseki (including data):
```bash
FUSEKI_APP=fuseki-app_test_fuseki_4-7-0
FUSEKI_DATA_APP=fuseki-data_test_fuseki_4-7-0

# stop running containers
docker stop "$FUSEKI_APP"
docker stop "$FUSEKI_DATA_APP"

# remove containers
docker rm "$FUSEKI_APP" "$FUSEKI_DATA_APP"

# check what images are still there, and remove unused ones 
# (here our custom jena-fuseki_customized-4-7-0)
docker images --all 
docker rmi jena-fuseki_customized-4-7-0 # remove also the afore bulit images
```

**Comment by infinite-dao** [comment]
Just a follow up: With version `4.7.0` I got it not working, the UI error was _«Last ping returned "AxiosError: Request failed with status code 404" in 13ms»_, it seems the problem with the jena fuseki 4.7.0, but version `4.4.0` worked as expected.
