### ISSUE TITLE
cp: cannot create regular file '/fuseki/shiro.ini': Permission denied

### ISSUE THREAD

**Issue by malakhovks** [stain/jena-docker#78]
Related to #77 

Running the image with commands:

- create volume container fuseki-data: 
   `$ docker run --name fuseki-data -v /fuseki busybox`
- run core image:
   `$ docker run --restart always --name fuseki -p 80:80 --volumes-from fuseki-data stain/jena-fuseki`

Results:
```
 ####################################
Initializing Apache Jena Fuseki

cp: cannot create regular file '/fuseki/shiro.ini': Permission denied
```

**System**

- OS Alpine Linux 3.18.2
- Docker version 23.0.6, build ef23cbc4315ae76c744e02d687c09548ede461bd

**Comment by malakhovks** [comment]
The version **4.0.0** `docker pull stain/jena-fuseki:4.0.0` from docker hub works, but the **latest** one does not.

Results:

```
 ####################################
Initializing Apache Jena Fuseki

cp: cannot create regular file '/fuseki/shiro.ini': Permission denied
```

**Comment by dwinston** [comment]
I have this same issue for `stain/jena-fuseki:4.8.0`, and I confirm that I do not have the issue for `stain/jena-fuseki:4.0.0`.

**Comment by Rulqu** [comment]
This is old docker problem with volumes when you're trying to use different user than root. There's almost no way to fix this for every scenario so I suggest you just upkeep your own dockerfiles. I fixed it this way: https://github.com/Rulqu/jena-docker/commit/d3436ae6d77cfe2aa14693b53309443123db1ab6

**Comment by rmeissn** [comment]
Executing `chown -R 100:101 /...` on your fuseki data (e.g. for a docker volume, use `/var/lib/docker/volumes/fuseki-data/_data/`) on your host OS resolved the issue for me. 100 and 101 correspond to the internal fuseki user of this image.

**Comment by stain** [comment]
For some reason you made the volume with `busybox` which didn't give you the right permissions, try instead:

    docker volume create fuseki-data
    docker run --restart always --name fuseki -p 3030:3030 --volume fuseki-data:/fuseki stain/jena-fuseki

Notice also port 80 not 3030
